"""Builds a synthetic RPG Maker project with real default sheet sizes and a unique colour per cell."""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

from rpgm_upscaler.core import crypto

KEY = bytes(range(16))


def grid_image(w, h, cw, ch, alpha=255):
    img = Image.new("RGBA", (w, h))
    px = img.load()
    for r in range(h // ch):
        for c in range(w // cw):
            col = ((c * 37 + 11) % 256, (r * 53 + 7) % 256, ((r * 7 + c) * 29) % 256, alpha)
            for y in range(r * ch, (r + 1) * ch):
                for x in range(c * cw, (c + 1) * cw):
                    px[x, y] = col
    return img


def _save(img, path: Path, encrypt=False, ext=".png_"):
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)
    if encrypt:
        data = crypto.encrypt(path.read_bytes(), KEY)
        path.unlink()
        path.with_suffix(ext).write_bytes(data)


def make_game(root: Path, engine="MZ", screen=(816, 624), encrypted=False, www=False) -> Path:
    web = root / "www" if www else root
    for d in ("js/plugins", "data", "img", "audio/bgm", "movies", "fonts", "css"):
        (web / d).mkdir(parents=True, exist_ok=True)
    (web / "index.html").write_text("<html></html>")
    if engine == "MZ":
        (web / "js/rmmz_core.js").write_text('Utils.RPGMAKER_NAME = "MZ"; Utils.RPGMAKER_VERSION = "1.8.0";')
        system = {"tileSize": 48, "hasEncryptedImages": encrypted, "hasEncryptedAudio": False,
                  "encryptionKey": KEY.hex(),
                  "advanced": {"screenWidth": screen[0], "screenHeight": screen[1],
                               "uiAreaWidth": screen[0], "uiAreaHeight": screen[1], "fontSize": 26,
                               "mainFontFilename": "x.ttf"}}
    else:
        (web / "js/rpg_core.js").write_text('Utils.RPGMAKER_NAME = "MV"; Utils.RPGMAKER_VERSION = "1.6.2";')
        (web / "js/rpg_managers.js").write_text(
            f"SceneManager._screenWidth  = {screen[0]};\nSceneManager._screenHeight = {screen[1]};\n")
        system = {"hasEncryptedImages": encrypted, "hasEncryptedAudio": False, "encryptionKey": KEY.hex()}
    (web / "data/System.json").write_text(json.dumps(system))
    (web / "data/Tilesets.json").write_text(json.dumps(
        [None, {"tilesetNames": ["World_A1", "", "", "", "Outside_A5", "Outside_B", "", "", ""]}]))
    (web / "js/plugins.js").write_text(
        '// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n'
        '{"name":"Foo","status":true,"description":"","parameters":{"x":"1"}},\n'
        '{"name":"Bar","status":false,"description":"","parameters":{}}\n];\n')
    pkg_dir = root
    (pkg_dir / "package.json").write_text(json.dumps({"name": "game", "main": "index.html",
                                                       "window": {"title": "", "width": screen[0], "height": screen[1]}}))
    (web / "audio/bgm/Theme.ogg").write_bytes(b"OggS-fake")
    (web / "fonts/x.ttf").write_bytes(b"font")
    img = web / "img"
    ext = ".png_" if engine == "MZ" else ".rpgmvp"
    for name, (w, h, cw, ch) in {
        "characters/Actor1": (576, 384, 48, 48), "characters/$Big": (144, 192, 48, 48),
        "faces/Actor1": (576, 288, 144, 144), "sv_actors/Actor1_1": (576, 384, 64, 64),
        "system/IconSet": (512, 64, 32, 32), "system/Window": (192, 192, 192, 192),
        "system/Balloon": (384, 720, 48, 48),
        "tilesets/World_A1": (768, 576, 24, 24), "tilesets/Outside_A5": (384, 768, 48, 48),
        "tilesets/Outside_B": (768, 768, 48, 48), "pictures/Pic": (200, 100, 200, 100),
        "titles1/Title": (816, 624, 408, 312), "battlebacks1/Grass": (1000, 740, 500, 370),
        "hud/Custom": (64, 64, 32, 32),
    }.items():
        _save(grid_image(w, h, cw, ch), img / f"{name}.png", encrypt=encrypted, ext=ext)
    # RGBA with transparency + palette mode
    t = grid_image(96, 96, 48, 48)
    t.paste((0, 0, 0, 0), (0, 0, 48, 96))
    _save(t, img / "pictures/Transparent.png", encrypt=encrypted, ext=ext)
    pal = Image.new("P", (32, 32)); pal.putpalette([255, 0, 0] * 256)
    _save(pal, img / "pictures/Palette.png", encrypt=encrypted, ext=ext)
    return root
